# Sources of sequences to include in the ingest run
sources: ['genbank']

# Params for the transform rule
transform:
  # Fields to rename.
  # This is the first step in the pipeline, so any references to field names
  # in the configs below should use the new field names
  field_map: ['collected=date', 'submitted=date_submitted', 'genbank_accession=accession']
  # Standardized strain name regex
  # Currently accepts any characters because we do not have a clear standard for strain names
  strain_regex: '^.+$'
  # Back up strain name field if 'strain' doesn't match regex above
  strain_backup_fields: ['accession']
  # Field to use as the sequence ID in the FASTA file
  id_field: 'strain'
  # Field to use as the sequence in the FASTA file
  sequence_field: 'sequence'
  # Final output columns for the metadata TSV
  metadata_columns: [
    'strain',
    'accession',
    'date',
    'region',
    'location',
    'host',
    'date_submitted'
  ]
