name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    uses: nextstrain/.github/.github/workflows/pathogen-repo-ci.yaml@master
    with:
      env: |
        NEXTSTRAIN_DOCKER_IMAGE: nextstrain/base
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ~3
    - run: pip install snakefmt
    - run: snakefmt --check .
